language: android

jdk: oraclejdk8
sudo: false
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - tools # appears twice as per Travis docs

    # The BuildTools version used by your project
    - build-tools-28.0.3 # latest build-tools ver sometimes doesn't work well with travis

    # The SDK version used to compile your project
    - android-28 # android 9.0 Pie

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-28
    - extra-android-support

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
